# -*- coding: utf-8 -*-
"""Procesamiento_Analitica_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hu6MyldLFc1Rtuy_ebv3muMaywUEikg8
"""

"""!pip install pipreqs openpyxl"""

## LIBRERÍAS (INICIO)
import glob
import os
from datetime import datetime
from functools import partial

import numpy as np
import pandas as pd

# --- FUNCIONES DE LIMPIEZA Y ESTANDARIZACIÓN ---


def clean_columns(df):
    """
    Función que limpia y estandariza los nombres de columna: minúsculas, sin espacios/puntos.
    """
    column_mapping = {}
    for col in df.columns:
        new_col = str(col).strip().lower()
        new_col = (
            new_col.replace(" ", "_")
            .replace(".", "")
            .replace("-", "_")
            .replace(":", "")
        )
        column_mapping[col] = new_col

    df.rename(columns=column_mapping, inplace=True)


###### Funciones para la carga de la información ######


def load_dataframe(year, sheet_name, ruta_informes, header=None):
    """
    Carga todos los archivos Excel correspondientes a un año.
    """
    pattern = os.path.join(ruta_informes, f"INFORMES DE VENTA CASAGRES*{year}.xls*")

    archivos_encontrados = glob.glob(pattern)

    if not archivos_encontrados:
        return []

    dataframes = []

    for archivo_excel in archivos_encontrados:
        print(f"  Cargando: {os.path.basename(archivo_excel)}")

        df = pd.read_excel(archivo_excel, sheet_name=sheet_name, header=header)

        dataframes.append(df)

    return dataframes


def load_all_dataframe(sheet_name, ruta_informes):
    """
    Carga todos los años, segrega las columnas principales de las columnas junk.
    Retorna dos DataFrames consolidados: (limpio, junk).
    """
    if sheet_name in ["REMISIONES", "Datos"]:
        header = 0
    elif sheet_name in ["INTERFACE PEDIDOS", "TERCEROS"]:
        header = 4
    else:
        print("El nombre de informe no se encuentra en la base de datos")
        header = 0

    years = ["2020", "2021", "2022", "2023", "2024", "2025", "2026"]

    raw_dataframes = []

    for year in years:
        dataframes_year = load_dataframe(
            year=year,
            sheet_name=sheet_name,
            ruta_informes=ruta_informes,
            header=header,
        )

        # Si no hay archivos para ese año, continuar
        if not dataframes_year:
            print(f"No se encontraron archivos para el año {year}. Se omite.")
            continue

        # Agregar todos los DataFrames encontrados
        raw_dataframes.extend(dataframes_year)

    columnas_limpias = [
        "referencia_producto",
        "descripcion_producto",
        "zona_vendedor",
        "nombre_zona_vendedor",
        "tercero",
        "nombre_tercero",
        "calificacion_tercero",
        "tipo_tercero",
        "lista_de_precio",
        "cod_ciudad",
        "sucursal_tercero",
        "periodo",
        "valor_neto",
        "cantidad",
        "cantidad_devolucion",
        "valor_venta",
        "cantidad_notas",
        "valor_notas",
        "tipo",
        "codigo_zona",
        "canal",
        "lista_de_precios",
        "departamento",
        "marca",
        "linea_inventarios",
        "descripcion_linea_inventarios",
        "grupo_inventarios",
        "descripcion_grupo_inventarios",
        "cod_producto",
        "descripcion",
        "clase_producto",
        "peso",
        "toneladas",
        "cantidad_neta",
        "valor_venta_neta",
        "valor_presupuesto",
        "dif",
        "precio",
        "valor_unitario",
        "diferencia",
        "precios_zonas",
        "precios_unicos",
        "periodo_precios",
        "meta_diaria_de_venta",
        "cumpli_proyect_$",
        "actual",
        "zona",
    ]

    clean_dfs = []
    junk_dfs = []
    NUM_COLS_ESPERADAS_HASTA_AT = 47

    for df in raw_dataframes:
        if df is None or df.empty:
            continue

        if len(df.columns) >= NUM_COLS_ESPERADAS_HASTA_AT:
            if "Nombre Zona Vendedor" in df.columns:
                df.rename(columns={df.columns[46]: "Zona"}, inplace=True)
                df["Zona"] = df["Nombre Zona Vendedor"]
            elif "Nombre Zona" in df.columns:
                df.rename(columns={df.columns[46]: "Zona"}, inplace=True)
                df["Zona"] = df["Nombre Zona"]
            elif "Nombre Zona Original" in df.columns:
                df.rename(columns={df.columns[46]: "Zona"}, inplace=True)
                df["Zona"] = df["Nombre Zona Original"]

        df_clean = df.iloc[:, :NUM_COLS_ESPERADAS_HASTA_AT].copy()

        # Ajustar nombres si la cantidad de columnas coincide con la lista esperada
        if len(df_clean.columns) == len(columnas_limpias):
            df_clean.columns = columnas_limpias

        clean_dfs.append(df_clean)

        df_junk = df.iloc[:, NUM_COLS_ESPERADAS_HASTA_AT:].copy()
        junk_dfs.append(df_junk)

    df_consolidado = pd.concat(clean_dfs, ignore_index=True)
    df_junk_consolidado = pd.concat(junk_dfs, ignore_index=True)

    if sheet_name in ["REMISIONES", "Datos"]:
        clean_columns(df_consolidado)

    return df_consolidado, df_junk_consolidado


##### Funciones para el procesamiento directo de DataFrames ######


def procesamiento_remisiones_y_facturas(df):
    if "periodo" in df.columns:
        df["periodo"] = pd.to_datetime(
            df["periodo"].dropna().astype(int).astype(str),
            format="%Y%m",
            errors="coerce",
        ).dt.to_period("M")

    if "referencia_producto" in df.columns:
        plantas = {
            "MC": "MINERALES CALDAS",
            "TG": "TECNIGRES",
            "TT": "TEJARES TERRACOTA",
            "CI": "CITG",
            "CO": "CO",
            "CP": "CP",
            "LS": "LSESTERILA",
            "IN": "INACTIVO",
            "PR": "PRESUPUESTO",
        }

        if "planta" in df.columns:
            df.drop(columns=["planta"], inplace=True)
        df["planta"] = df["referencia_producto"].astype(str).str[:2].map(plantas)

    return df


# --- SCRIPT DE EJECUCIÓN PRINCIPAL ---


def ejecutar_etl_ventas(ruta_informes, ruta_salida):
    SHEET_NAME_VENTAS = "Datos"

    print(f"\n--- INICIO DEL PROCESAMIENTO ETL ---")

    try:
        # 1. Cargar y concatenar
        df_consolidado, df_junk_consolidado = load_all_dataframe(
            sheet_name=SHEET_NAME_VENTAS, ruta_informes=ruta_informes
        )
        print("\n Carga finalizada. Datos concatenados.")

        # 2. Aplicar el procesamiento al DF limpio
        df_limpio = procesamiento_remisiones_y_facturas(df_consolidado)

        # 3. Validación
        columna_valor = "valor_venta"
        if columna_valor in df_limpio.columns:
            gran_total = df_limpio[columna_valor].sum()

            if "planta" in df_limpio.columns:
                totales_por_planta = (
                    df_limpio.groupby("planta")[columna_valor]
                    .sum()
                    .sort_values(ascending=False)
                )
                print(f"\n--- VALIDACIÓN FINAL ({columna_valor} corregido) ---")
                print(totales_por_planta.apply(lambda x: f"{x:,.2f}").to_string())
                print("-" * 35)
                print(f" GRAN TOTAL DE VENTAS: {gran_total:,.2f}")
                print("-" * 35)

        # 4. Exportar el DataFrame limpio
        nombre_archivo_salida = os.path.join(
            ruta_salida,
            "Ventas_Casagres_Limpio_PowerBI.xlsx",
        )

        df_limpio.iloc[:, :48].to_excel(
            nombre_archivo_salida, index=False, engine="openpyxl"
        )
        print(
            f"\n EXPORTACIÓN EXITOSA: Archivo guardado como '{nombre_archivo_salida}'"
        )

    except FileNotFoundError as e:
        print(f"\n ERROR CRÍTICO DE ARCHIVO: {e}")
    except Exception as e:
        import traceback

        print("\nOcurrió un error inesperado durante el procesamiento:")
        traceback.print_exc()


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--carpeta-datos",
        type=str,
        default=r"C:\source\casagres\Casagres.API\proyecto_icmd",
        help="Carpeta que contiene 'informes/' y donde se guardará el Excel limpio.",
    )
    args = parser.parse_args()

    ejecutar_etl_ventas(
        ruta_informes=os.path.join(args.carpeta_datos, "informes"),
        ruta_salida=args.carpeta_datos,
    )
